export const images = {
  bitcoinIsland: `/images/bitcoin-island.webp`,
  blogPreview: `/images/blog-preview.webp`,
  dogma: `/images/dogma.webp`,
  dvadesetJedan: `/images/dvadeset-jedan.webp`,
  magicInternetMoney: `/images/magic-internet-money.webp`,
  meetupCover: `/images/meetup-cover.webp`,
  meetup: `/images/meetup.webp`,
  player: `/images/player.webp`,
  dearFamilyDearFriends: `/images/content/dear-family.jpeg`,
  hero1: `/images/hero_1.webp`,
  hero2: `/images/hero_2.webp`,
  hero3: `/images/hero_3.webp`,
  hero4: `/images/hero_4.webp`,
  hero5: `/images/hero_5.webp`,
  "bullishcase-featured": `/images/content/bullishcase-featured.jpg`,
  "bitcoin-ne-moze-biti-zabranjen-featured": `/images/content/bitcoin-ne-moze-biti-zabranjen-featured.png`,
  "zasto-je-vazna-decentralizacija-bitcoina": `/images/content/zasto-je-vazna-decentralizacija-bitcoina.png`,
  "bitcoin-privatnost-najbolje-prakse": `/images/content/bitcoin-privatnost-najbolje-prakse.png`,
  "bitcoin-daje-ti-krila": `/images/content/bitcoin-daje-ti-krila.png`,
  "bitcoin-je-vrijeme": `/images/content/bitcoin-je-vrijeme.png`,
  "borba-protiv-monetarnog-kolonijalizma-pomocu-otvorenog-koda": `/images/content/borba-protiv-monetarnog-kolonijalizma-pomocu-otvorenog-koda.jpeg`,
  "selo-i-mocnik": `/images/content/selo-i-mocnik.jpeg`,

} as const;
