export const images = {
  bitcoinIsland: `/images/bitcoin-island.webp`,
  blogPreview: `/images/blog-preview.webp`,
  dogma: `/images/dogma.webp`,
  dvadesetJedan: `/images/dvadeset-jedan.webp`,
  magicInternetMoney: `/images/magic-internet-money.webp`,
  meetupCover: `/images/meetup-cover.webp`,
  meetup: `/images/meetup.webp`,
  player: `/images/player.webp`,
  dearFamilyDearFriends: `/images/content/dear-family.jpeg`,
  hero1: `/images/hero_1.webp`,
  hero2: `/images/hero_2.webp`,
  hero3: `/images/hero_3.webp`,
  hero4: `/images/hero_4.webp`,
  hero5: `/images/hero_5.webp`,
  "bullishcase-featured": `/images/content/bullishcase-featured.jpg`,
  "bitcoin-ne-moze-biti-zabranjen-featured": `/images/content/bitcoin-ne-moze-biti-zabranjen-featured.png`,
  "btc-decentralizacija-featured.png": `/images/content/btc-decentralizacija-featured.png`,
} as const;
